version: "3.9"

services:
  backend:
    command: yarn start:dev
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    container_name: lipso-backend-dev
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
